/* 주식 */
DROP TABLE TYAH001 
	CASCADE CONSTRAINTS;

f
/* 주식-배당 */
DROP TABLE TYAH004 
	CASCADE CONSTRAINTS;

/* 주식-가격이력 */
DROP TABLE TYAH005 
	CASCADE CONSTRAINTS;

/* 주식-배당이력 */
DROP TABLE TYAH006 
	CASCADE CONSTRAINTS;

/* 포트폴리오 */
DROP TABLE TPOR001 
	CASCADE CONSTRAINTS;

/* 포트폴리오-구성 */
DROP TABLE TPOR002 
	CASCADE CONSTRAINTS;

/* 포트폴리오-수익률(일) */
DROP TABLE TSUM001 
	CASCADE CONSTRAINTS;

/* 포트폴리오-수익율(월) */
DROP TABLE TSUM002 
	CASCADE CONSTRAINTS;

/* 포트폴리오-수익률(년) */
DROP TABLE TSUM003 
	CASCADE CONSTRAINTS;

/* 주식-환률 */
DROP TABLE TYAH007 
	CASCADE CONSTRAINTS;

/* 주식-분류코드 */
DROP TABLE TSTC001 
	CASCADE CONSTRAINTS;

/* 주식-분류 */
DROP TABLE TSTC002 
	CASCADE CONSTRAINTS;

/* 주식 */
CREATE TABLE TYAH001 (
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	NAME VARCHAR2(100), /* 이름 */
	CURRENCY VARCHAR2(40), /* 통화 */
	STOCK_EXCHANGE VARCHAR2(50), /* 거래소 */
	REG_DATE VARCHAR2(17), /* 등록일 */
	MOD_DATE VARCHAR2(17) /* 수정일 */
);

COMMENT ON TABLE TYAH001 IS '주식';

COMMENT ON COLUMN TYAH001.SYMBOL IS '심볼';

COMMENT ON COLUMN TYAH001.NAME IS '이름';

COMMENT ON COLUMN TYAH001.CURRENCY IS '통화';

COMMENT ON COLUMN TYAH001.STOCK_EXCHANGE IS '거래소';

COMMENT ON COLUMN TYAH001.REG_DATE IS '등록일';

COMMENT ON COLUMN TYAH001.MOD_DATE IS '수정일';

CREATE UNIQUE INDEX PK_TYAH001
	ON TYAH001 (
		SYMBOL ASC
	);

ALTER TABLE TYAH001
	ADD
		CONSTRAINT PK_TYAH001
		PRIMARY KEY (
			SYMBOL
		);

/* 주식-기본정보 */
CREATE TABLE TYAH002 (
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	GET_DATE VARCHAR2(8) NOT NULL, /* 수집일 */
	ASK DECIMAL(13,5), /* 매수가 */
	ASK_SIZE INTEGER, /* 매수량 */
	BID DECIMAL(13,5), /* 매도가 */
	BID_SIZE INTEGER, /* 매도량 */
	PRICE DECIMAL(13,5), /* 가격 */
	LAST_TRADE_TIME VARCHAR2(17), /* 최종매매일시 */
	OPEN DECIMAL(13,5), /* 개장가 */
	PREVIOUS_CLOSE DECIMAL(13,5), /* 이전마감가 */
	DAY_HEIGH DECIMAL(13,5), /* 장중최고가 */
	DAY_LOW DECIMAL(13,5), /* 장중최저가 */
	YEAR_HIGH DECIMAL(13,5), /* 년중최고가 */
	YEAR_LOW DECIMAL(13,5), /* 년중최저가 */
	PRICE_AVG50 DECIMAL(13,5), /* 50일평균가 */
	PRICE_AVG200 DECIMAL(13,5), /* 200일평균가 */
	VOLUME INTEGER, /* 거래량 */
	AVG_VOLUME INTEGER, /* 평균거래량 */
	CHANGE DECIMAL(13,5), /* 응락금액 */
	CHANGE_PER DECIMAL(13,5), /* 등락율 */
	CHANGE_YEAR_LOW DECIMAL(13,5), /* 최저등락금액(년) */
	CHANGE_YEAR_LOW_PER DECIMAL(13,5), /* 최저등락율(년) */
	CHANGE_YEAR_HIGH DECIMAL(13,5), /* 최고등락금액(년) */
	CHANGE_YEAR_HIGH_PER DECIMAL(13,5), /* 최고등락율(년) */
	CHANGE_AVG50 DECIMAL(13,5), /* 50일평균등락금액 */
	CHANGE_AVG50_PER DECIMAL(13,5), /* 50일평균등락율 */
	CHANGE_AVG200 DECIMAL(13,5), /* 200일평균등락금액 */
	CHANGE_AVG200_PER DECIMAL(13,5), /* 200일평균등락율 */
	REG_DATE VARCHAR2(17), /* 등록일 */
	MOD_DATE VARCHAR2(17) /* 수정일 */
);

COMMENT ON TABLE TYAH002 IS '주식-기본정보';

COMMENT ON COLUMN TYAH002.SYMBOL IS '심볼';

COMMENT ON COLUMN TYAH002.GET_DATE IS '수집일';

COMMENT ON COLUMN TYAH002.ASK IS '매수가';

COMMENT ON COLUMN TYAH002.ASK_SIZE IS '매수량';

COMMENT ON COLUMN TYAH002.BID IS '매도가';

COMMENT ON COLUMN TYAH002.BID_SIZE IS '매도량';

COMMENT ON COLUMN TYAH002.PRICE IS '가격';

COMMENT ON COLUMN TYAH002.LAST_TRADE_TIME IS '최종매매일시';

COMMENT ON COLUMN TYAH002.OPEN IS '개장가';

COMMENT ON COLUMN TYAH002.PREVIOUS_CLOSE IS '이전마감가';

COMMENT ON COLUMN TYAH002.DAY_HEIGH IS '장중최고가';

COMMENT ON COLUMN TYAH002.DAY_LOW IS '장중최저가';

COMMENT ON COLUMN TYAH002.YEAR_HIGH IS '년중최고가';

COMMENT ON COLUMN TYAH002.YEAR_LOW IS '년중최저가';

COMMENT ON COLUMN TYAH002.PRICE_AVG50 IS '50일평균가';

COMMENT ON COLUMN TYAH002.PRICE_AVG200 IS '200일평균가';

COMMENT ON COLUMN TYAH002.VOLUME IS '거래량';

COMMENT ON COLUMN TYAH002.AVG_VOLUME IS '평균거래량';

COMMENT ON COLUMN TYAH002.CHANGE IS '응락금액';

COMMENT ON COLUMN TYAH002.CHANGE_PER IS '등락율';

COMMENT ON COLUMN TYAH002.CHANGE_YEAR_LOW IS '최저등락금액(년)';

COMMENT ON COLUMN TYAH002.CHANGE_YEAR_LOW_PER IS '최저등락율(년)';

COMMENT ON COLUMN TYAH002.CHANGE_YEAR_HIGH IS '최고등락금액(년)';

COMMENT ON COLUMN TYAH002.CHANGE_YEAR_HIGH_PER IS '최고등락율(년)';

COMMENT ON COLUMN TYAH002.CHANGE_AVG50 IS '50일평균등락금액';

COMMENT ON COLUMN TYAH002.CHANGE_AVG50_PER IS '50일평균등락율';

COMMENT ON COLUMN TYAH002.CHANGE_AVG200 IS '200일평균등락금액';

COMMENT ON COLUMN TYAH002.CHANGE_AVG200_PER IS '200일평균등락율';

COMMENT ON COLUMN TYAH002.REG_DATE IS '등록일';

COMMENT ON COLUMN TYAH002.MOD_DATE IS '수정일';

CREATE UNIQUE INDEX PK_TYAH002
	ON TYAH002 (
		SYMBOL ASC
	);

ALTER TABLE TYAH002
	ADD
		CONSTRAINT PK_TYAH002
		PRIMARY KEY (
			SYMBOL
		);

/* 주식-펀더먼탈 */
CREATE TABLE TYAH003 (
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	GET_DATE VARCHAR2(8) NOT NULL, /* 수집일 */
	MARKET_CAP NUMBER(15), /* 시가총액 */
	SHARES NUMBER(15), /* 유통주식수 */
	EPS DECIMAL(13,5), /* 주당이익 */
	PE DECIMAL(13,5), /* 주가수익율 */
	PEG DECIMAL(13,5), /* 주가매출액증가율 */
	EPS_EST_CURR_YEAR DECIMAL(13,5), /* 예상주가수익(금년) */
	EPS_EST_NEXT_QUARTER DECIMAL(13,5), /* 예상주가수익(다음분기) */
	EPS_EST_NEXT_YEAR DECIMAL(13,5), /* 예상주가수익(내년) */
	PRICE_BOOK DECIMAL(13,5), /* 장부가 */
	BOOK_VALUE_PER_PRICE DECIMAL(13,5), /* 주당자산가치 */
	REVENUE NUMBER(15), /* 자산 */
	ONE_YEAR_TARGET_PRICE DECIMAL(13,5), /* 목표가(년) */
	EARNINGS_ANNOUNCEMENT VARCHAR2(8), /* 매출발표일시 */
	ROE DECIMAL(13,5), /* ROE */
	EBITDA DECIMAL(13,5), /* EBITDA */
	REG_DATE VARCHAR2(17), /* 등록일 */
	MOD_DATE VARCHAR2(17) /* 수정일 */
);

COMMENT ON TABLE TYAH003 IS '주식-펀더먼탈';

COMMENT ON COLUMN TYAH003.SYMBOL IS '심볼';

COMMENT ON COLUMN TYAH003.GET_DATE IS '수집일';

COMMENT ON COLUMN TYAH003.MARKET_CAP IS '시가총액';

COMMENT ON COLUMN TYAH003.SHARES IS '유통주식수';

COMMENT ON COLUMN TYAH003.EPS IS '주당이익';

COMMENT ON COLUMN TYAH003.PE IS '주가수익율';

COMMENT ON COLUMN TYAH003.PEG IS '주가매출액증가율';

COMMENT ON COLUMN TYAH003.EPS_EST_CURR_YEAR IS '예상주가수익(금년)';

COMMENT ON COLUMN TYAH003.EPS_EST_NEXT_QUARTER IS '예상주가수익(다음분기)';

COMMENT ON COLUMN TYAH003.EPS_EST_NEXT_YEAR IS '예상주가수익(내년)';

COMMENT ON COLUMN TYAH003.PRICE_BOOK IS '장부가';

COMMENT ON COLUMN TYAH003.BOOK_VALUE_PER_PRICE IS '주당자산가치';

COMMENT ON COLUMN TYAH003.REVENUE IS '자산';

COMMENT ON COLUMN TYAH003.ONE_YEAR_TARGET_PRICE IS '목표가(년)';

COMMENT ON COLUMN TYAH003.EARNINGS_ANNOUNCEMENT IS '매출발표일시';

COMMENT ON COLUMN TYAH003.ROE IS 'ROE';

COMMENT ON COLUMN TYAH003.EBITDA IS 'EBITDA';

COMMENT ON COLUMN TYAH003.REG_DATE IS '등록일';

COMMENT ON COLUMN TYAH003.MOD_DATE IS '수정일';

CREATE UNIQUE INDEX PK_TYAH003
	ON TYAH003 (
		SYMBOL ASC
	);

ALTER TABLE TYAH003
	ADD
		CONSTRAINT PK_TYAH003
		PRIMARY KEY (
			SYMBOL
		);

/* 주식-배당 */
CREATE TABLE TYAH004 (
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	PAY_DATE VARCHAR2(17) NOT NULL, /* 지급일시 */
	EX_DATE VARCHAR2(8), /* 배당확정일 */
	ANNUAL_YIELD DECIMAL(13,5), /* 연배당수익 */
	ANNUAL_YIELD_PER DECIMAL(13,5), /* 연배당수익율 */
	REG_DATE VARCHAR2(17), /* 등록일 */
	MOD_DATE VARCHAR2(17) /* 수정일 */
);

COMMENT ON TABLE TYAH004 IS '주식-배당';

COMMENT ON COLUMN TYAH004.SYMBOL IS '심볼';

COMMENT ON COLUMN TYAH004.PAY_DATE IS '지급일시';

COMMENT ON COLUMN TYAH004.EX_DATE IS '배당확정일';

COMMENT ON COLUMN TYAH004.ANNUAL_YIELD IS '연배당수익';

COMMENT ON COLUMN TYAH004.ANNUAL_YIELD_PER IS '연배당수익율';

COMMENT ON COLUMN TYAH004.REG_DATE IS '등록일';

COMMENT ON COLUMN TYAH004.MOD_DATE IS '수정일';

CREATE UNIQUE INDEX PK_TYAH004
	ON TYAH004 (
		SYMBOL ASC,
		PAY_DATE ASC
	);

ALTER TABLE TYAH004
	ADD
		CONSTRAINT PK_TYAH004
		PRIMARY KEY (
			SYMBOL,
			PAY_DATE
		);

/* 주식-가격이력 */
CREATE TABLE TYAH005 (
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	TRADE_DATE VARCHAR2(8) NOT NULL, /* 거래일 */
	OPEN DECIMAL(13,5), /* 개장가 */
	LOW DECIMAL(13,5), /* 저가 */
	HIGH DECIMAL(13,5), /* 고가 */
	CLOSE DECIMAL(13,5), /* 종가 */
	ADJ_CLOSE DECIMAL(13,5), /* 조정종가 */
	VOLUME INTEGER /* 거래량 */
);

COMMENT ON TABLE TYAH005 IS '주식-가격이력';

COMMENT ON COLUMN TYAH005.SYMBOL IS '심볼';

COMMENT ON COLUMN TYAH005.TRADE_DATE IS '거래일';

COMMENT ON COLUMN TYAH005.OPEN IS '개장가';

COMMENT ON COLUMN TYAH005.LOW IS '저가';

COMMENT ON COLUMN TYAH005.HIGH IS '고가';

COMMENT ON COLUMN TYAH005.CLOSE IS '종가';

COMMENT ON COLUMN TYAH005.ADJ_CLOSE IS '조정종가';

COMMENT ON COLUMN TYAH005.VOLUME IS '거래량';

CREATE UNIQUE INDEX PK_TYAH005
	ON TYAH005 (
		SYMBOL ASC,
		TRADE_DATE ASC
	);

ALTER TABLE TYAH005
	ADD
		CONSTRAINT PK_TYAH005
		PRIMARY KEY (
			SYMBOL,
			TRADE_DATE
		);

/* 주식-배당이력 */
CREATE TABLE TYAH006 (
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	DIVIDEND_DATE VARCHAR2(8) NOT NULL, /* 배당일시 */
	ADJ_DIVIDEND DECIMAL(13,5) /* 배당금 */
);

COMMENT ON TABLE TYAH006 IS '주식-배당이력';

COMMENT ON COLUMN TYAH006.SYMBOL IS '심볼';

COMMENT ON COLUMN TYAH006.DIVIDEND_DATE IS '배당일시';

COMMENT ON COLUMN TYAH006.ADJ_DIVIDEND IS '배당금';

CREATE UNIQUE INDEX PK_TYAH006
	ON TYAH006 (
		SYMBOL ASC,
		DIVIDEND_DATE ASC
	);

ALTER TABLE TYAH006
	ADD
		CONSTRAINT PK_TYAH006
		PRIMARY KEY (
			SYMBOL,
			DIVIDEND_DATE
		);

/* 포트폴리오 */
CREATE TABLE TPOR001 (
	PORTFOLIO_ID VARCHAR2(50) NOT NULL, /* 포트폴리오ID */
	NAME VARCHAR2(100), /* 이름 */
	REG_DATE VARCHAR2(17), /* 등록일 */
	MOD_DATE VARCHAR2(17) /* 수정일 */
);

COMMENT ON TABLE TPOR001 IS '포트폴리오';

COMMENT ON COLUMN TPOR001.PORTFOLIO_ID IS '포트폴리오ID';

COMMENT ON COLUMN TPOR001.NAME IS '이름';

COMMENT ON COLUMN TPOR001.REG_DATE IS '등록일';

COMMENT ON COLUMN TPOR001.MOD_DATE IS '수정일';

CREATE UNIQUE INDEX PK_TPOR001
	ON TPOR001 (
		PORTFOLIO_ID ASC
	);

ALTER TABLE TPOR001
	ADD
		CONSTRAINT PK_TPOR001
		PRIMARY KEY (
			PORTFOLIO_ID
		);

/* 포트폴리오-구성 */
CREATE TABLE TPOR002 (
	PORTFOLIO_ID VARCHAR2(50) NOT NULL, /* 포트폴리오ID */
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	TRADE_DAY VARCHAR2(8) NOT NULL, /* 거래일 */
	PRICE DECIMAL(13,5), /* 단가 */
	QTY INTEGER, /* 수량 */
	AMT NUMBER(13) /* 금액 */
);

COMMENT ON TABLE TPOR002 IS '포트폴리오-구성';

COMMENT ON COLUMN TPOR002.PORTFOLIO_ID IS '포트폴리오ID';

COMMENT ON COLUMN TPOR002.SYMBOL IS '심볼';

COMMENT ON COLUMN TPOR002.TRADE_DAY IS '거래일';

COMMENT ON COLUMN TPOR002.PRICE IS '단가';

COMMENT ON COLUMN TPOR002.QTY IS '수량';

COMMENT ON COLUMN TPOR002.AMT IS '금액';

CREATE UNIQUE INDEX PK_TPOR002
	ON TPOR002 (
		PORTFOLIO_ID ASC,
		SYMBOL ASC,
		TRADE_DAY ASC
	);

ALTER TABLE TPOR002
	ADD
		CONSTRAINT PK_TPOR002
		PRIMARY KEY (
			PORTFOLIO_ID,
			SYMBOL,
			TRADE_DAY
		);

/* 포트폴리오-수익률(일) */
CREATE TABLE TSUM001 (
	PORTFOLIO_ID VARCHAR2(50) NOT NULL, /* 포트폴리오ID */
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	DAY VARCHAR2(8) NOT NULL, /* 거래일 */
	QTY INTEGER, /* 매입수량 */
	AVG_PRICE DECIMAL(13,5), /* 평균매입단가 */
	AMT NUMBER(13), /* 매입금액 */
	CUR_AMT NUMBER(13), /* 평가금액 */
	EARNING_RATE DECIMAL(13,5) /* 수익률 */
);

COMMENT ON TABLE TSUM001 IS '포트폴리오-수익률(일)';

COMMENT ON COLUMN TSUM001.PORTFOLIO_ID IS '포트폴리오ID';

COMMENT ON COLUMN TSUM001.SYMBOL IS '심볼';

COMMENT ON COLUMN TSUM001.DAY IS '거래일';

COMMENT ON COLUMN TSUM001.QTY IS '매입수량';

COMMENT ON COLUMN TSUM001.AVG_PRICE IS '평균매입단가';

COMMENT ON COLUMN TSUM001.AMT IS '매입금액';

COMMENT ON COLUMN TSUM001.CUR_AMT IS '평가금액';

COMMENT ON COLUMN TSUM001.EARNING_RATE IS '수익률';

CREATE UNIQUE INDEX PK_TSUM001
	ON TSUM001 (
		PORTFOLIO_ID ASC,
		SYMBOL ASC,
		DAY ASC
	);

ALTER TABLE TSUM001
	ADD
		CONSTRAINT PK_TSUM001
		PRIMARY KEY (
			PORTFOLIO_ID,
			SYMBOL,
			DAY
		);

/* 포트폴리오-수익율(월) */
CREATE TABLE TSUM002 (
	PORTFOLIO_ID VARCHAR2(50) NOT NULL, /* 포트폴리오ID */
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	TRADE_DAY VARCHAR2(8) NOT NULL, /* 거래일 */
	MONTH VARCHAR2(8), /* 거래월 */
	QTY INTEGER, /* 매입수량 */
	AVG_PRICE DECIMAL(13,5), /* 평균매입단가 */
	AMT NUMBER(13), /* 매입금액 */
	CUR_AMT NUMBER(13), /* 평가금액 */
	EARNING_RATE DECIMAL(13,5) /* 수익률 */
);

COMMENT ON TABLE TSUM002 IS '포트폴리오-수익율(월)';

COMMENT ON COLUMN TSUM002.PORTFOLIO_ID IS '포트폴리오ID';

COMMENT ON COLUMN TSUM002.SYMBOL IS '심볼';

COMMENT ON COLUMN TSUM002.TRADE_DAY IS '거래일';

COMMENT ON COLUMN TSUM002.MONTH IS '거래월';

COMMENT ON COLUMN TSUM002.QTY IS '매입수량';

COMMENT ON COLUMN TSUM002.AVG_PRICE IS '평균매입단가';

COMMENT ON COLUMN TSUM002.AMT IS '매입금액';

COMMENT ON COLUMN TSUM002.CUR_AMT IS '평가금액';

COMMENT ON COLUMN TSUM002.EARNING_RATE IS '수익률';

CREATE UNIQUE INDEX PK_TSUM002
	ON TSUM002 (
		PORTFOLIO_ID ASC,
		SYMBOL ASC,
		TRADE_DAY ASC
	);

ALTER TABLE TSUM002
	ADD
		CONSTRAINT PK_TSUM002
		PRIMARY KEY (
			PORTFOLIO_ID,
			SYMBOL,
			TRADE_DAY
		);

/* 포트폴리오-수익률(년) */
CREATE TABLE TSUM003 (
	PORTFOLIO_ID VARCHAR2(50) NOT NULL, /* 포트폴리오ID */
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	TRADE_DAY VARCHAR2(8) NOT NULL, /* 거래일 */
	YEAR VARCHAR2(8), /* 거래년 */
	QTY INTEGER, /* 매입수량 */
	AVG_PRICE DECIMAL(13,5), /* 평균매입단가 */
	AMT NUMBER(13), /* 매입금액 */
	CUR_AMT NUMBER(13), /* 평가금액 */
	EARNING_RATE DECIMAL(13,5) /* 수익률 */
);

COMMENT ON TABLE TSUM003 IS '포트폴리오-수익률(년)';

COMMENT ON COLUMN TSUM003.PORTFOLIO_ID IS '포트폴리오ID';

COMMENT ON COLUMN TSUM003.SYMBOL IS '심볼';

COMMENT ON COLUMN TSUM003.TRADE_DAY IS '거래일';

COMMENT ON COLUMN TSUM003.YEAR IS '거래년';

COMMENT ON COLUMN TSUM003.QTY IS '매입수량';

COMMENT ON COLUMN TSUM003.AVG_PRICE IS '평균매입단가';

COMMENT ON COLUMN TSUM003.AMT IS '매입금액';

COMMENT ON COLUMN TSUM003.CUR_AMT IS '평가금액';

COMMENT ON COLUMN TSUM003.EARNING_RATE IS '수익률';

CREATE UNIQUE INDEX PK_TSUM003
	ON TSUM003 (
		PORTFOLIO_ID ASC,
		SYMBOL ASC,
		TRADE_DAY ASC
	);

ALTER TABLE TSUM003
	ADD
		CONSTRAINT PK_TSUM003
		PRIMARY KEY (
			PORTFOLIO_ID,
			SYMBOL,
			TRADE_DAY
		);

/* 주식-환률 */
CREATE TABLE TYAH007 (
	SYMBOL VARCHAR2(10) NOT NULL, /* 환율심볼 */
	GET_DAY VARCHAR2(8) NOT NULL, /* 일자 */
	PRICE DECIMAL(13,5), /* 환율 */
	REG_DATE VARCHAR2(17), /* 등록일 */
	MOD_DATE VARCHAR2(17) /* 수정일 */
);

COMMENT ON TABLE TYAH007 IS '주식-환률';

COMMENT ON COLUMN TYAH007.SYMBOL IS '환율심볼';

COMMENT ON COLUMN TYAH007.GET_DAY IS '일자';

COMMENT ON COLUMN TYAH007.PRICE IS '환율';

COMMENT ON COLUMN TYAH007.REG_DATE IS '등록일';

COMMENT ON COLUMN TYAH007.MOD_DATE IS '수정일';

CREATE UNIQUE INDEX PK_TYAH007
	ON TYAH007 (
		SYMBOL ASC,
		GET_DAY ASC
	);

ALTER TABLE TYAH007
	ADD
		CONSTRAINT PK_TYAH007
		PRIMARY KEY (
			SYMBOL,
			GET_DAY
		);

/* 주식-분류코드 */
CREATE TABLE TSTC001 (
	LEVEL VARCHAR2(5) NOT NULL, /* 부문코드 */
	CD VARCHAR2(5) NOT NULL, /* 분류코드 */
	LEVEL_NM VARCHAR2(100) NOT NULL, /* 부문코드명 */
	NM VARCHAR2(100), /* 분류코드명 */
	VAL VARCHAR2(255), /* 분류코드값 */
	REG_DATE VARCHAR2(17), /* 등록일 */
	MOD_DATE VARCHAR2(17) /* 수정일 */
);

COMMENT ON TABLE TSTC001 IS '주식-분류코드';

COMMENT ON COLUMN TSTC001.LEVEL IS '부문코드';

COMMENT ON COLUMN TSTC001.CD IS '분류코드';

COMMENT ON COLUMN TSTC001.LEVEL_NM IS '부문코드명';

COMMENT ON COLUMN TSTC001.NM IS '분류코드명';

COMMENT ON COLUMN TSTC001.VAL IS '분류코드값';

COMMENT ON COLUMN TSTC001.REG_DATE IS '등록일';

COMMENT ON COLUMN TSTC001.MOD_DATE IS '수정일';

CREATE UNIQUE INDEX PK_TSTC001
	ON TSTC001 (
		LEVEL ASC,
		CD ASC
	);

ALTER TABLE TSTC001
	ADD
		CONSTRAINT PK_TSTC001
		PRIMARY KEY (
			LEVEL,
			CD
		);

/* 주식-분류 */
CREATE TABLE TSTC002 (
	SYMBOL VARCHAR2(10) NOT NULL, /* 심볼 */
	MARKET_CD VARCHAR2(5), /* 시장분류코드1 */
	ASSET_CD VARCHAR2(5), /* 자산분류코드2 */
	PRODUCT_CD VARCHAR2(5) /* 상품분류코드3 */
);

COMMENT ON TABLE TSTC002 IS '주식-분류';

COMMENT ON COLUMN TSTC002.SYMBOL IS '심볼';

COMMENT ON COLUMN TSTC002.MARKET_CD IS '시장분류코드1';

COMMENT ON COLUMN TSTC002.ASSET_CD IS '자산분류코드2';

COMMENT ON COLUMN TSTC002.PRODUCT_CD IS '상품분류코드3';

CREATE UNIQUE INDEX PK_TSTC002
	ON TSTC002 (
		SYMBOL ASC
	);

ALTER TABLE TSTC002
	ADD
		CONSTRAINT PK_TSTC002
		PRIMARY KEY (
			SYMBOL
		);

ALTER TABLE TYAH002
	ADD
		CONSTRAINT FK_TYAH001_TO_TYAH002
		FOREIGN KEY (
			SYMBOL
		)
		REFERENCES TYAH001 (
			SYMBOL
		);

ALTER TABLE TYAH003
	ADD
		CONSTRAINT FK_TYAH001_TO_TYAH003
		FOREIGN KEY (
			SYMBOL
		)
		REFERENCES TYAH001 (
			SYMBOL
		);

ALTER TABLE TYAH004
	ADD
		CONSTRAINT FK_TYAH001_TO_TYAH004
		FOREIGN KEY (
			SYMBOL
		)
		REFERENCES TYAH001 (
			SYMBOL
		);

ALTER TABLE TYAH005
	ADD
		CONSTRAINT FK_TYAH001_TO_TYAH005
		FOREIGN KEY (
			SYMBOL
		)
		REFERENCES TYAH001 (
			SYMBOL
		);

ALTER TABLE TYAH006
	ADD
		CONSTRAINT FK_TYAH001_TO_TYAH006
		FOREIGN KEY (
			SYMBOL
		)
		REFERENCES TYAH001 (
			SYMBOL
		);

ALTER TABLE TPOR002
	ADD
		CONSTRAINT FK_TPOR001_TO_TPOR002
		FOREIGN KEY (
			PORTFOLIO_ID
		)
		REFERENCES TPOR001 (
			PORTFOLIO_ID
		);

ALTER TABLE TPOR002
	ADD
		CONSTRAINT FK_TYAH001_TO_TPOR002
		FOREIGN KEY (
			SYMBOL
		)
		REFERENCES TYAH001 (
			SYMBOL
		);

ALTER TABLE TSTC002
	ADD
		CONSTRAINT FK_TYAH001_TO_TSTC002
		FOREIGN KEY (
			SYMBOL
		)
		REFERENCES TYAH001 (
			SYMBOL
		);



