-- sector 별 포지션 
SELECT 
	 BL.SYMBOL 
	,BL.AVG_PRICE
	,BL.QTY
	,BL.AMT
	,PC."CLOSE" 
	,BL.QTY  * pc."CLOSE" AS CUR_AMT
  FROM (
	SELECT 
		 a.PORTFOLIO_ID 
		,a.SYMBOL  
		,avg(a.PRICE ) 			AS AVG_PRICE
		,sum(a.QTY)				AS QTY
		,sum(a.QTY * a.PRICE ) 	AS AMT
	  FROM TPOR002 a
	GROUP BY a.PORTFOLIO_ID , a.SYMBOL  
) BL
INNER JOIN tyah005 PC 
ON BL.SYMBOL = PC.SYMBOL 
AND PC.TRADE_DATE = (SELECT max(t2.TRADE_DATE) FROM TYAH005 t2 WHERE t2.SYMBOL = pc.SYMBOL );

 
	